//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Process
{
	using Model;
	using Presentation;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GameController
	{
		public virtual LobbyView lobbyView
		{
			get;
			set;
		}

		public virtual LevelView levelView
		{
			get;
			set;
		}

		public virtual Game game
		{
			get;
			set;
		}

        public static List<char> SwitchButtons = new List<char>()
        {
            'A',
            'S',
            'D',
            'X',
            'C'
        };

  

		public virtual void Stop()
		{
			throw new System.NotImplementedException();
		}

	    public GameController()
	    {
            // create models
            game = new Game();
	        game.Timer.Elapsed += new System.Timers.ElapsedEventHandler((source, e) => onTick());

            // create Views
            levelView = new LevelView();
            lobbyView = new LobbyView();
        }

		public virtual void Start()
		{
            lobbyView.ShowWelcome();

            Run();
		}

		public virtual void Run()
		{
            
            game.Run();
            levelView.Print(game.Board);

		    while (true) // TODO cleaner way of net shutting down application
		    {
		       char key = Char.ToUpper(InputController.AskUserInput());

		       //SwitchTile sw = game.Board.Field[5][7] as SwitchTile;
               //Console.WriteLine("\n"+sw.Direction.y);

		        int index = GetKeyIndex(key);

                // Validation necessary
                if(index != -1)
                Board.Switches[index].Switch();

                //Console.WriteLine(sw.Direction.y);

                var collection = game.Board.Field.GetAll<WaterTile>();
		    
            } 
        }

	    public virtual void onTick()
	    {
            levelView.Print(game.Board);
        }

	    public int GetKeyIndex(char key)
	    {
	        return SwitchButtons.FindIndex(x => x == key);
	    }
	}
}

