//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Process
{
	using Model;
	using Presentation;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GameController
	{
		public virtual LobbyView lobbyView
		{
			get;
			set;
		}

		public virtual LevelView levelView
		{
			get;
			set;
		}

		public virtual object inputController
		{
			get;
			set;
		}

		public virtual Game game
		{
			get;
			set;
		}

		public virtual void Stop()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Start()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Run()
		{
			throw new System.NotImplementedException();
		}

	}
}

