//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Presentation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputController
	{
		public static Char AskUserInput()
		{
		    var key = Console.ReadKey().KeyChar;
		    return key;
		}

	}
}

