//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GoudkoortsModelLib.GeneratedCode.Presentation;
using Model;

namespace Presentation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class LevelView
	{

		public virtual void Print(Board board)
		{
            Console.Clear();
            Console.WriteLine("Time :" + Math.Round(board.Game.TimeTick / 1000f));
		    Console.WriteLine();

            foreach (List<Tile> row in board.Field)
		    {
		        foreach (Tile tile in row)
		        {
		            Console.Write(TileView.Create(tile));
		        }
                Console.WriteLine();
		    }
		}

	}
}

