//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Presentation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class LobbyView
	{
		public virtual void ShowWelcome()
		{
			// TODO
            Console.WriteLine("Druk op een key om het spel te beginnen");
		    Console.ReadKey();
            Console.Clear();
		}

	}
}

