//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;

namespace Helper
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FileParser
	{
        public static IEnumerable<string> readFileLines(string path)
        {
            string line;
            using (var reader = File.OpenText(path))
            {
                while ((line = reader.ReadLine()) != null)
                {
                    yield return line;
                }
            }
        }
    }
}

