//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BaanVak : Vak
	{
		public virtual Kar Kar
		{
			get;
			set;
		}

	    public Loods Wharf
	    {
	        get; set;
        }

	    public BaanVak(int row, int column, char symbol)
	    {
	        this.Row = row;
	        this.Column = column;
	        this.Symbol = symbol;
	    }

	}
}

