//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GoudkoortsModelLib.GeneratedCode.Model;
using Microsoft.Win32;

namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Cart : MovingObject
	{
		public virtual bool isEmpty
		{
			get;
			set;
		}

        public bool MoveAble // Groene strook
        {
            set;
            get;
        }

        public RailTile Tile
        {
            get;
            set;
        }

        public Cart(RailTile tile)
        {
            Tile = tile;
        }

        public override void Tick()
        {
            if (!MoveAble)
                return;

            // Move Cart
            Move();
            // Psuedo code
            // Get next BaanVak : Vak.Board.SetVak(this, Vak.Coords + Vak.Direction);
        }

	    public override void Move()
	    {
            //TODO Check if we can get rid of the cast
	        Tile tile = Tile.Board.Field.Get(Tile.Coords + Tile.Direction);

	        if (tile is RailTile)
	        {
	            RailTile nextTile = (RailTile)tile;

	            if (!nextTile.IsOccupied())
	            {
	                Tile.Contain = null;
                    nextTile.Contain = this;
	            }
	            else
	            {
                    //TODO collision

	            }
	        }
	    }
    }
}

