//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Cart : ITickAble
	{
		public virtual bool isEmpty
		{
			get;
			set;
		}

        public bool MoveAble // Groene strook
        {
            set;
            get;
        }

        public RailTile Tile
        {
            get;
            set;
        }

        public Cart(RailTile tile)
        {
            Tile = tile;
        }

		public virtual void Tick()
		{
            if (!MoveAble)
                return;

            // Move Ship

            // Psuedo code
            // Get next BaanVak : Vak.Board.SetVak(this, Vak.Coords + Vak.Direction);
        }

    }
}

