//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System;

	public interface ITickAble
	{
        // What to do for every tick
		void Tick();
	}
}

