//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Kar : iUpdateable
	{
		public virtual bool isEmpty
		{
			get;
			set;
		}

        public bool MoveAble // Groene strook
        {
            set;
            get;
        }

        public BaanVak Vak
        {
            get;
            set;
        }

        public Kar(BaanVak vak)
        {
            Vak = vak;
        }

		public virtual void Update()
		{
            if (!MoveAble)
                return;

            // Move Ship

            // Psuedo code
            // Get next BaanVak : Vak.Board.SetVak(this, Vak.Coords + Vak.Direction);
        }

    }
}

