//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class RailTile : Tile
	{
        public override Object Contain
        {
            get { return _contain; }
            set
            {
                if (value is Boat)
                    _contain = value;
                else
                    throw new ArgumentException();
            }
        }

        public RailTile(Point coords, char symbol, Board board = null) : base(coords, board)
	    {
	        this.Symbol = symbol;
	    }

	}
}

