//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SailTile : WaterTile, IDirection
	{
	    public Point Direction { get; set; }

        public SailTile(Point coords, Board board = null) : base(coords, board)
        {
            this.Coords = coords;
            this.Board = board;
        }

        public override Object Contain
        {
            get { return _contain; }
            set
            {
                if(value is Boat)
                    _contain = value;
                else
                    throw new ArgumentException();
            }
        }

    }
}

