//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;

namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Timers;

	public class Storage : ITickAble, IRunAble
    {
        private static int SPAWN_TIME = 8000;

        private Timer timer;

        public Tile Tile
        {
            set;
            get;
        }
        public Storage(Tile tile)
        {
            Tile = tile;

            // Create timer
            timer = new Timer();
            timer.Elapsed += new ElapsedEventHandler((source, e) => Tick());
            timer.Interval = SPAWN_TIME;
        }

        public void spawnCart()
        {
            // Psuedo code
            // Spawn a cart : Vak.Board.placeObject(this, Vak.Coords + new Point(1, 0)); // BaanVak always right of Loods
            RailTile tile = (RailTile)Tile.Board.Field.Get(Tile.Coords + Point.Right);

            if (!tile.IsOccupied())
                Environment.Exit(0); // TODO
            else
                tile.Contain = new Cart(tile);

            Debug.Write("Cart spawned");
        }

        public void Tick()
        {
            spawnCart();
        }

        public void Run()
        {
            timer.Enabled = true;
        }
    }
}

