//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Drawing;

	public class Tile
	{
       
        public Point Coords { get; set; }

        public Board Board { get; set; }

	    public Tile(Point coords, Board board = null)
	    {
            Coords = coords;
	        Board = board;
	    }



	}
}

