//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Drawing;

	public class Vak
	{
        // Het symbool van het desbetreffende vakje
        public char Symbol { get; set; }

        public Point Coords { get; set; }

        public Board Board { get; set; }

	    public Vak(int row, int column, Board board = null)
	    {
	        Coords.x = row;
	        Coords.y = column;
	        Board = board;
	    }

	}
}

